[package]
name = "jour-20"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
comfy-table = "7.2.1"
eyre = "0.6.12"
rand = "0.9.2"
walkdir = "2.5.0"
